server {
    listen 80;
    server_name _;
    index index.php;

    charset utf-8;

    # Docker DNS — nginx стартует даже если app ещё не поднят
    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        set $php_upstream app:9000;
        include fastcgi_params;
        fastcgi_pass $php_upstream;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
